
FROM golang:latest

ADD . /reservation-api

WORKDIR /reservation-api
RUN go mod init reservation-api
RUN go mod tidy
RUN go build -o reservation-api
RUN chmod +x /reservation-api

EXPOSE 3001

ENTRYPOINT ["./reservation-api"]